name: Deploy to My Server via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to My Server via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: 80.85.153.48  # Замените на IP-адрес вашего сервера
        username: ${{ secrets.FTP_USERNAME }}  # Добавьте секрет с именем FTP_USERNAME в настройках вашего репозитория на GitHub
        password: ${{ secrets.FTP_PASSWORD }}  # Добавьте секрет с именем FTP_PASSWORD в настройках вашего репозитория на GitHub
        local-dir: ./  # Указание текущего каталога для загрузки
        server-dir: /var/www/html/  # Укажите удаленный каталог на вашем сервере
        protocol: ftp  # Использование FTP (можно заменить на ftps или sftp при необходимости)
