name: Deploy to My Server via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to My Server via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: 80.85.153.48
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /var/www/html/
        protocol: ftps
        passive: true
