name: Deploy to My Server via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to My Server via SFTP
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: 80.85.153.48
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        script: |
          cd /var/www/html/
          put -r ./
